Repository QuiltMC/enigma, pull requests merged in 2023-07, with the labels that each got.

#117 make enigma legal
  CHANGES.md
  COPYING.md
Labels: documentation

#119 fix name conflict detection
  enigma-swing/src/main/java/cuchaz/enigma/gui/GuiController.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/NotificationManager.java
  enigma/src/main/java/cuchaz/enigma/analysis/StructureTreeNode.java
  enigma/src/main/java/cuchaz/enigma/translation/Translatable.java
  enigma/src/main/java/cuchaz/enigma/translation/Translator.java
  enigma/src/main/java/cuchaz/enigma/translation/mapping/EntryRemapper.java
  enigma/src/main/java/cuchaz/enigma/translation/mapping/MappingValidator.java
  enigma/src/main/java/cuchaz/enigma/translation/representation/entry/ClassEntry.java
  enigma/src/main/java/cuchaz/enigma/translation/representation/entry/Entry.java
  enigma/src/main/java/cuchaz/enigma/translation/representation/entry/MethodEntry.java
  enigma/src/main/java/cuchaz/enigma/utils/validation/Message.java
  enigma/src/main/java/cuchaz/enigma/utils/validation/ValidationContext.java
  enigma/src/main/resources/lang/de_de.json
  enigma/src/main/resources/lang/en_us.json
  enigma/src/main/resources/lang/fr_fr.json
  enigma/src/main/resources/lang/ja_jp.json
  enigma/src/test/java/cuchaz/enigma/inputs/validation/BaseClass.java
  enigma/src/test/java/cuchaz/enigma/inputs/validation/SuperClass.java
  enigma/src/test/java/cuchaz/enigma/translation/mapping/TestMappingValidator.java
Labels: bug, backend

#121 Quiltflower -> Vineflower
  CHANGES.md
  README.md
  build.gradle
  enigma-swing/src/main/java/cuchaz/enigma/gui/config/Decompiler.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/config/DecompilerConfig.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/config/UiConfig.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/dialog/AboutDialog.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/dialog/decompiler/VineflowerSettingsDialog.java
  enigma/build.gradle
  enigma/src/main/java/cuchaz/enigma/Enigma.java
  enigma/src/main/java/cuchaz/enigma/analysis/BuiltinPlugin.java
  enigma/src/main/java/cuchaz/enigma/source/Decompilers.java
  enigma/src/main/java/cuchaz/enigma/source/vineflower/EnigmaContextSource.java
  enigma/src/main/java/cuchaz/enigma/source/vineflower/EnigmaFernflowerLogger.java
  enigma/src/main/java/cuchaz/enigma/source/vineflower/EnigmaJavadocProvider.java
  enigma/src/main/java/cuchaz/enigma/source/vineflower/EnigmaResultSaver.java
  enigma/src/main/java/cuchaz/enigma/source/vineflower/EnigmaTextTokenCollector.java
  enigma/src/main/java/cuchaz/enigma/source/vineflower/VineflowerDecompiler.java
  enigma/src/main/java/cuchaz/enigma/source/vineflower/VineflowerPreferences.java
  enigma/src/main/java/cuchaz/enigma/source/vineflower/VineflowerSource.java
  enigma/src/main/resources/lang/en_us.json
  enigma/src/main/resources/lang/fr_fr.json
  enigma/src/test/java/cuchaz/enigma/DecompilationTest.java
  enigma/src/test/java/cuchaz/enigma/TestJarIndexBridgeMethods.java
  gradle/libs.versions.toml
Labels: backend, refactor

#126 automatic mapping format detection
  enigma-cli/src/main/java/cuchaz/enigma/command/Command.java
  enigma-cli/src/main/java/cuchaz/enigma/command/DropInvalidMappingsCommand.java
  enigma-server/src/main/java/cuchaz/enigma/network/DedicatedEnigmaServer.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/GuiController.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/elements/MenuBar.java
  enigma/src/main/java/cuchaz/enigma/translation/mapping/serde/MappingFormat.java
  enigma/src/main/resources/lang/en_us.json
  enigma/src/test/java/cuchaz/enigma/MappingFormatDetectionTest.java
  enigma/src/test/resources/formats/enigma_directory_example_mapping/TestClass.mapping
  enigma/src/test/resources/formats/enigma_file_example_mapping.mapping
  enigma/src/test/resources/formats/enigma_zip_example_mapping.zip
  enigma/src/test/resources/formats/proguard_example_mapping.txt
  enigma/src/test/resources/formats/recaf_example_mapping.txt
  enigma/src/test/resources/formats/srg_file_example_mapping.tsrg
  enigma/src/test/resources/formats/tiny_file_example_mapping.tiny
  enigma/src/test/resources/formats/tiny_v2_example_mapping.tiny
Labels: backend, refactor
