Repository QuiltMC/enigma, pull requests merged in 2023-04, with the labels that each got.

#80 properly invalidate stats when updating class tree
  enigma-swing/src/main/java/cuchaz/enigma/gui/ClassSelector.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/GuiController.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/util/GuiUtil.java
Labels: bug, user interface

#84 Optimize NestedPackages by deferring sorting
  enigma-swing/src/main/java/cuchaz/enigma/gui/NestedPackages.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/node/ClassSelectorPackageNode.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/node/SortedMutableTreeNode.java
Labels: enhancement, user interface

#88 fix #82
  enigma-swing/src/main/java/cuchaz/enigma/gui/GuiController.java
Labels: bug, user interface

#83 Fix StringIndexOutOfBoundsException when loading non UNIX file path
  enigma/src/main/java/cuchaz/enigma/utils/validation/ParameterizedMessage.java
Labels: bug, backend

#90 reload parent of updated class node upon stat reload completion
  enigma-swing/src/main/java/cuchaz/enigma/gui/node/ClassSelectorClassNode.java
Labels: bug, user interface

#92 fix mapping stats skipping lambda parameters
  enigma-swing/src/main/java/cuchaz/enigma/gui/stats/StatsGenerator.java
Labels: bug, user interface
