Repository QuiltMC/enigma, pull requests merged in 2023-06, with the labels that each got.

#107 add an option to hide all progress bars
  enigma-swing/src/main/java/cuchaz/enigma/gui/Gui.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/GuiController.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/Main.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/dialog/ProgressDialog.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/dialog/StatsDialog.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/elements/ClassSelectorPopupMenu.java
  enigma-swing/src/test/java/cuchaz/enigma/TestPackageRename.java
Labels: enhancement, user interface

#97 add class selector tooltips and improve stat generation
  enigma-swing/src/main/java/cuchaz/enigma/gui/ClassSelector.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/Gui.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/GuiController.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/NestedPackages.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/dialog/StatsDialog.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/node/ClassSelectorClassNode.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/panels/EditorPanel.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/stats/StatsGenerator.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/stats/StatsMember.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/stats/StatsResult.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/util/GuiUtil.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/util/StatsManager.java
  enigma/build.gradle
  enigma/src/main/java/cuchaz/enigma/stats/StatType.java
  enigma/src/main/java/cuchaz/enigma/stats/StatsGenerator.java
  enigma/src/main/java/cuchaz/enigma/stats/StatsResult.java
  enigma/src/main/resources/lang/en_us.json
  enigma/src/test/java/cuchaz/enigma/TestStatsGeneration.java
Labels: bug, enhancement, backend, user interface

#101 refactor dockers to be non-static
  enigma-swing/src/main/java/cuchaz/enigma/gui/Gui.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/GuiController.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/NotificationManager.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/config/UiConfig.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/dialog/SearchDialog.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/docker/CollabDocker.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/docker/Dock.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/docker/Docker.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/docker/DockerManager.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/docker/component/DockerSelector.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/docker/component/DockerTitleBar.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/elements/ClassSelectorPopupMenu.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/elements/MainWindow.java
  enigma-swing/src/test/java/cuchaz/enigma/TestPackageRename.java
Labels: enhancement, user interface

#114 fix enum statistics counting
  enigma/src/main/java/cuchaz/enigma/Enigma.java
  enigma/src/main/java/cuchaz/enigma/EnigmaProject.java
  enigma/src/main/java/cuchaz/enigma/analysis/StructureTreeNode.java
  enigma/src/main/java/cuchaz/enigma/analysis/index/BridgeMethodIndex.java
  enigma/src/main/java/cuchaz/enigma/analysis/index/IndexClassVisitor.java
  enigma/src/main/java/cuchaz/enigma/bytecode/translators/LocalVariableFixVisitor.java
  enigma/src/main/java/cuchaz/enigma/source/DecompiledClassSource.java
  enigma/src/main/java/cuchaz/enigma/stats/StatsGenerator.java
  enigma/src/main/java/cuchaz/enigma/translation/representation/ArgumentDescriptor.java
  enigma/src/main/java/cuchaz/enigma/translation/representation/MethodDescriptor.java
  enigma/src/main/java/cuchaz/enigma/translation/representation/ParameterAccessFlags.java
  enigma/src/test/java/cuchaz/enigma/TestJarIndexEnums.java
  enigma/src/test/java/cuchaz/enigma/inputs/enums/Color.java
  enigma/src/test/java/cuchaz/enigma/inputs/enums/TestEnum.java
  enigma/src/test/resources/proguard-enums-test.conf
Labels: bug, backend

#115 French translations
  enigma/src/main/resources/lang/fr_fr.json
Labels: translation
