Repository QuiltMC/enigma, pull requests merged in 2023-08, with the labels that each got.

#135 remove access modifier editing
  enigma-server/docs/protocol.md
  enigma-server/src/main/java/cuchaz/enigma/network/packet/PacketHelper.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/panels/IdentifierPanel.java
  enigma/src/main/java/cuchaz/enigma/translation/mapping/AccessModifier.java
  enigma/src/main/java/cuchaz/enigma/translation/mapping/EntryChange.java
  enigma/src/main/java/cuchaz/enigma/translation/mapping/EntryMapping.java
  enigma/src/main/java/cuchaz/enigma/translation/mapping/EntryUtil.java
  enigma/src/main/java/cuchaz/enigma/translation/mapping/MappingsChecker.java
  enigma/src/main/java/cuchaz/enigma/translation/mapping/serde/RawEntryMapping.java
  enigma/src/main/java/cuchaz/enigma/translation/mapping/serde/enigma/EnigmaMappingsReader.java
  enigma/src/main/java/cuchaz/enigma/translation/mapping/serde/enigma/EnigmaMappingsWriter.java
  enigma/src/main/java/cuchaz/enigma/translation/representation/entry/ClassDefEntry.java
  enigma/src/main/java/cuchaz/enigma/translation/representation/entry/FieldDefEntry.java
  enigma/src/main/java/cuchaz/enigma/translation/representation/entry/MethodDefEntry.java
  enigma/src/main/resources/lang/en_us.json
  enigma/src/main/resources/lang/fr_fr.json
  enigma/src/main/resources/lang/ja_jp.json
  enigma/src/main/resources/lang/zh_cn.json
Labels: backend, removal

#137 Ensure Tiny V2 always writes in the same order
  enigma/src/main/java/cuchaz/enigma/translation/mapping/serde/tinyv2/TinyV2Writer.java
  enigma/src/main/java/cuchaz/enigma/translation/representation/entry/ClassEntry.java
  enigma/src/test/java/cuchaz/enigma/TestEntryOrdering.java
  enigma/src/test/java/cuchaz/enigma/translation/mapping/TestDeterministicWrite.java
Labels: enhancement, backend

#138 remove tiny v1 and improve commands to use automatic format detection
  enigma-cli/src/main/java/cuchaz/enigma/command/Command.java
  enigma-cli/src/main/java/cuchaz/enigma/command/ComposeMappingsCommand.java
  enigma-cli/src/main/java/cuchaz/enigma/command/ConvertMappingsCommand.java
  enigma-cli/src/main/java/cuchaz/enigma/command/FillClassMappingsCommand.java
  enigma-cli/src/main/java/cuchaz/enigma/command/InsertProposedMappingsCommand.java
  enigma-cli/src/main/java/cuchaz/enigma/command/InvertMappingsCommand.java
  enigma-cli/src/main/java/cuchaz/enigma/command/MapSpecializedMethodsCommand.java
  enigma-cli/src/main/java/cuchaz/enigma/command/MappingCommandsUtil.java
  enigma-cli/src/test/java/cuchaz/enigma/command/FillClassMappingsCommandTest.java
  enigma-cli/src/test/java/cuchaz/enigma/command/MapSpecializedMethodsCommandTest.java
  enigma-server/src/main/java/cuchaz/enigma/network/DedicatedEnigmaServer.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/GuiController.java
  enigma/src/main/java/cuchaz/enigma/translation/mapping/serde/MappingFormat.java
  enigma/src/main/java/cuchaz/enigma/translation/mapping/serde/MappingsReader.java
  enigma/src/main/java/cuchaz/enigma/translation/mapping/serde/MappingsWriter.java
  enigma/src/main/java/cuchaz/enigma/translation/mapping/serde/enigma/EnigmaMappingsReader.java
  enigma/src/main/java/cuchaz/enigma/translation/mapping/serde/proguard/ProguardMappingsReader.java
  enigma/src/main/java/cuchaz/enigma/translation/mapping/serde/recaf/RecafMappingsReader.java
  enigma/src/main/java/cuchaz/enigma/translation/mapping/serde/tiny/TinyMappingsReader.java
  enigma/src/main/java/cuchaz/enigma/translation/mapping/serde/tiny/TinyMappingsWriter.java
  enigma/src/main/java/cuchaz/enigma/translation/mapping/serde/tinyv2/TinyV2Reader.java
  enigma/src/test/java/cuchaz/enigma/TestTranslator.java
  enigma/src/test/java/cuchaz/enigma/translation/mapping/TestComments.java
  enigma/src/test/java/cuchaz/enigma/translation/mapping/TestReadWriteCycle.java
  enigma/src/test/java/cuchaz/enigma/translation/mapping/TestTinyV2InnerClasses.java
  enigma/src/test/java/cuchaz/enigma/translation/mapping/TestV2Main.java
  enigma/src/test/java/cuchaz/enigma/translation/mapping/serde/recaf/TestRecaf.java
  enigma/src/test/resources/formats/tiny_file_example_mapping.tiny
Labels: enhancement, backend, removal

#142 improve command help
  enigma-cli/build.gradle
  enigma-cli/src/main/java/cuchaz/enigma/command/Argument.java
  enigma-cli/src/main/java/cuchaz/enigma/command/CheckMappingsCommand.java
  enigma-cli/src/main/java/cuchaz/enigma/command/Command.java
  enigma-cli/src/main/java/cuchaz/enigma/command/ComposeMappingsCommand.java
  enigma-cli/src/main/java/cuchaz/enigma/command/ComposedArgument.java
  enigma-cli/src/main/java/cuchaz/enigma/command/ConvertMappingsCommand.java
  enigma-cli/src/main/java/cuchaz/enigma/command/DecompileCommand.java
  enigma-cli/src/main/java/cuchaz/enigma/command/DeobfuscateCommand.java
  enigma-cli/src/main/java/cuchaz/enigma/command/DropInvalidMappingsCommand.java
  enigma-cli/src/main/java/cuchaz/enigma/command/FillClassMappingsCommand.java
  enigma-cli/src/main/java/cuchaz/enigma/command/HelpCommand.java
  enigma-cli/src/main/java/cuchaz/enigma/command/InsertProposedMappingsCommand.java
  enigma-cli/src/main/java/cuchaz/enigma/command/InvertMappingsCommand.java
  enigma-cli/src/main/java/cuchaz/enigma/command/Main.java
  enigma-cli/src/main/java/cuchaz/enigma/command/MapSpecializedMethodsCommand.java
  enigma-cli/src/main/java/cuchaz/enigma/command/MappingCommandsUtil.java
Labels: enhancement, cli

#143 Fix regex for renaming package with a capital letter
  enigma-swing/src/main/java/cuchaz/enigma/gui/elements/ClassSelectorPopupMenu.java
Labels: enhancement, user interface
