Repository QuiltMC/enigma, pull requests merged in 2023-05, with the labels that each got.

#85 more info in "Processing..." step in jar indexing
  enigma/src/main/java/cuchaz/enigma/analysis/index/BridgeMethodIndex.java
  enigma/src/main/java/cuchaz/enigma/analysis/index/EnclosingMethodIndex.java
  enigma/src/main/java/cuchaz/enigma/analysis/index/EntryIndex.java
  enigma/src/main/java/cuchaz/enigma/analysis/index/InheritanceIndex.java
  enigma/src/main/java/cuchaz/enigma/analysis/index/JarIndex.java
  enigma/src/main/java/cuchaz/enigma/analysis/index/JarIndexer.java
  enigma/src/main/java/cuchaz/enigma/analysis/index/PackageVisibilityIndex.java
  enigma/src/main/java/cuchaz/enigma/analysis/index/ReferenceIndex.java
  enigma/src/main/resources/lang/en_us.json
  enigma/src/main/resources/lang/fr_fr.json
  enigma/src/main/resources/lang/ja_jp.json
  enigma/src/main/resources/lang/zh_cn.json
Labels: enhancement, backend

#95 make quiltflower default
  enigma-swing/src/main/java/cuchaz/enigma/gui/config/UiConfig.java
  gradle/libs.versions.toml
Labels: enhancement, user interface

#93 allow searching multiple entry types simultaneously
  enigma-swing/src/main/java/cuchaz/enigma/gui/config/keybind/KeyBinds.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/dialog/SearchDialog.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/elements/MenuBar.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/search/SearchEntry.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/search/SearchUtil.java
  enigma/src/main/resources/lang/en_us.json
Labels: enhancement, user interface

#86 show custom indexer progress
  enigma/src/main/java/cuchaz/enigma/Enigma.java
  enigma/src/main/java/cuchaz/enigma/EnigmaServices.java
  enigma/src/main/resources/lang/en_us.json
Labels: enhancement, backend

#98 fix some docker-related issues
  enigma-swing/src/main/java/cuchaz/enigma/gui/Gui.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/docker/Dock.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/elements/EditorTabbedPane.java
Labels: bug, enhancement, user interface

#102 Show inner classes in bytecode view
  enigma/src/main/java/cuchaz/enigma/source/bytecode/BytecodeDecompiler.java
  enigma/src/main/java/cuchaz/enigma/source/bytecode/BytecodeSource.java
  enigma/src/main/java/cuchaz/enigma/source/bytecode/EnigmaTextifier.java
Labels: enhancement, user interface

#96 class tree improvements and fixes
  enigma-cli/build.gradle
  enigma-cli/src/test/java/cuchaz/enigma/command/CheckMappingsCommandTest.java
  enigma-cli/src/test/java/cuchaz/enigma/command/CommandTest.java
  enigma-cli/src/test/java/cuchaz/enigma/command/FillClassMappingsCommandTest.java
  enigma-cli/src/test/java/cuchaz/enigma/command/MapSpecializedMethodsCommandTest.java
  enigma-swing/build.gradle
  enigma-swing/src/main/java/cuchaz/enigma/gui/ClassSelector.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/Gui.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/GuiController.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/Main.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/NestedPackages.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/dialog/CrashDialog.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/dialog/JavadocDialog.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/dialog/SearchDialog.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/dialog/StatsDialog.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/docker/AllClassesDocker.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/docker/ClassesDocker.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/docker/DeobfuscatedClassesDocker.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/docker/Dock.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/docker/ObfuscatedClassesDocker.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/elements/ClassSelectorPopupMenu.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/elements/DeobfPanelPopupMenu.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/elements/EditorPopupMenu.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/elements/MenuBar.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/node/ClassSelectorClassNode.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/node/ClassSelectorPackageNode.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/panels/EditorPanel.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/panels/IdentifierPanel.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/util/GuiUtil.java
  enigma-swing/src/test/java/cuchaz/enigma/PackageRenameTest.java
  enigma-swing/src/test/resources/test_mappings/E.mapping
  enigma-swing/src/test/resources/test_mappings/a/D.mapping
  enigma-swing/src/test/resources/test_mappings/a/b/C.mapping
  enigma-swing/src/test/resources/test_mappings/a/b/c/A.mapping
  enigma-swing/src/test/resources/test_mappings/a/b/c/B.mapping
  enigma/build.gradle
  enigma/src/main/java/cuchaz/enigma/utils/validation/Message.java
  enigma/src/main/java/cuchaz/enigma/utils/validation/ValidationContext.java
  enigma/src/main/resources/lang/en_us.json
  enigma/src/main/resources/lang/fr_fr.json
  enigma/src/main/resources/lang/ja_jp.json
  enigma/src/testFixtures/java/cuchaz/enigma/TestEntryFactory.java
  enigma/src/testFixtures/java/cuchaz/enigma/TestUtil.java
Labels: bug, enhancement, user interface

#105 implement crash history
  enigma-swing/src/main/java/cuchaz/enigma/gui/ExceptionIgnorer.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/Gui.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/Main.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/dialog/CrashDialog.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/dialog/ProgressDialog.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/elements/ClassSelectorPopupMenu.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/elements/MenuBar.java
  enigma/src/main/resources/lang/en_us.json
Labels: enhancement, user interface
