Repository QuiltMC/enigma, pull requests merged in 2023-03, with the labels that each got.

#68 make `superClass` in `ClassDefEntry` explicitly nullable
  enigma/src/main/java/cuchaz/enigma/translation/representation/entry/ClassDefEntry.java
Labels: bug, backend

#69 most likely fix #12
  enigma-swing/src/main/java/cuchaz/enigma/gui/EnigmaQuickFindDialog.java
Labels: bug, user interface

#72 ignore entries that no longer exist from recent files in gui
  enigma-swing/src/main/java/cuchaz/enigma/gui/elements/MenuBar.java
Labels: bug, user interface

#71 fix inner classes displaying far too many class names
  enigma/src/main/java/cuchaz/enigma/source/SourceRemapper.java
  enigma/src/main/java/cuchaz/enigma/source/Token.java
  enigma/src/main/java/cuchaz/enigma/translation/representation/entry/ClassEntry.java
Labels: bug, user interface

#73 Remove `readUTF` references
  enigma-server/src/main/java/cuchaz/enigma/network/ServerMessage.java
  enigma-server/src/main/java/cuchaz/enigma/network/packet/UserListS2CPacket.java
Labels: bug, server

#79 some quick style fixes
  enigma-swing/src/main/java/cuchaz/enigma/gui/ClassSelector.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/EditableType.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/EnigmaQuickFindDialog.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/EnigmaSyntaxKit.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/Gui.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/GuiController.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/Main.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/NotificationManager.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/QuickFindAction.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/TokenListCellRenderer.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/config/UiConfig.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/config/keybind/KeyBind.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/config/keybind/KeyBinds.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/dialog/AboutDialog.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/dialog/AbstractDialog.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/dialog/CrashDialog.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/dialog/FontDialog.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/dialog/JavadocDialog.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/dialog/ProgressDialog.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/dialog/SearchDialog.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/dialog/StatsDialog.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/dialog/decompiler/QuiltflowerSettingsDialog.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/dialog/keybind/CombinationPanel.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/dialog/keybind/ConfigureCategoryKeyBindsDialog.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/dialog/keybind/EditKeyBindDialog.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/docker/CollabDocker.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/docker/Dock.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/docker/ObfuscatedClassesDocker.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/docker/StructureDocker.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/docker/component/DockerButton.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/docker/component/DockerSelector.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/elements/ConvertingTextField.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/elements/EditorPopupMenu.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/elements/JMultiLineToolTip.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/elements/MenuBar.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/elements/StatusBar.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/events/ThemeChangeListener.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/highlight/SelectionHighlightPainter.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/node/ClassSelectorClassNode.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/node/ClassSelectorPackageNode.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/panels/ClosableTabTitlePane.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/panels/EditorPanel.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/panels/IdentifierPanel.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/renderer/CallsTreeCellRenderer.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/renderer/ImplementationsTreeCellRenderer.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/renderer/MessageListCellRenderer.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/search/SearchEntry.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/search/SearchUtil.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/stats/StatsGenerator.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/util/AbstractListCellRenderer.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/util/GuiUtil.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/util/ScaleChangeListener.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/util/ScaleUtil.java
Labels: user interface

#81 fix bad disconnect messages
  enigma-server/src/main/java/cuchaz/enigma/network/EnigmaClient.java
  enigma-server/src/main/java/cuchaz/enigma/network/EnigmaServer.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/GuiController.java
Labels: bug, user interface
