Repository QuiltMC/enigma, pull requests merged in 2023-02, with the labels that each got.

#30 use tinylog for logging instead of `System.out`
  build.gradle
  enigma-cli/src/main/java/cuchaz/enigma/command/CheckMappingsCommand.java
  enigma-cli/src/main/java/cuchaz/enigma/command/Command.java
  enigma-cli/src/main/java/cuchaz/enigma/command/DecompileCommand.java
  enigma-cli/src/main/java/cuchaz/enigma/command/DropInvalidMappingsCommand.java
  enigma-cli/src/main/java/cuchaz/enigma/command/InsertProposedMappingsCommand.java
  enigma-cli/src/main/java/cuchaz/enigma/command/Main.java
  enigma-server/src/main/java/cuchaz/enigma/network/DedicatedEnigmaServer.java
  enigma-server/src/main/java/cuchaz/enigma/network/EnigmaClient.java
  enigma-server/src/main/java/cuchaz/enigma/network/EnigmaServer.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/Gui.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/GuiController.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/Main.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/config/UiConfig.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/config/keybind/KeyBind.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/dialog/CrashDialog.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/panels/EditorPanel.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/util/ScaleUtil.java
  enigma/src/main/java/cuchaz/enigma/EnigmaProfile.java
  enigma/src/main/java/cuchaz/enigma/EnigmaProject.java
  enigma/src/main/java/cuchaz/enigma/config/ConfigContainer.java
  enigma/src/main/java/cuchaz/enigma/source/procyon/index/TokenFactory.java
  enigma/src/main/java/cuchaz/enigma/translation/LocalNameGenerator.java
  enigma/src/main/java/cuchaz/enigma/translation/mapping/EntryMapping.java
  enigma/src/main/java/cuchaz/enigma/translation/mapping/serde/enigma/EnigmaMappingsWriter.java
  enigma/src/main/java/cuchaz/enigma/translation/mapping/serde/recaf/RecafMappingsWriter.java
  enigma/src/main/java/cuchaz/enigma/translation/mapping/serde/srg/SrgMappingsWriter.java
  enigma/src/main/java/cuchaz/enigma/translation/mapping/serde/tiny/TinyMappingsWriter.java
  enigma/src/main/java/cuchaz/enigma/translation/mapping/serde/tinyv2/TinyV2Writer.java
  enigma/src/main/java/cuchaz/enigma/utils/I18n.java
  enigma/src/main/java/cuchaz/enigma/utils/validation/PrintValidatable.java
  enigma/src/main/java/cuchaz/enigma/utils/validation/ValidationContext.java
  enigma/src/main/resources/tinylog.properties
  enigma/src/test/java/cuchaz/enigma/TokenChecker.java
  gradle/libs.versions.toml
Labels: enhancement, backend, user interface, server

#35 add a resize button to dockers
  enigma-swing/src/main/java/cuchaz/enigma/gui/docker/Dock.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/docker/Docker.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/docker/component/DockerTitleBar.java
Labels: enhancement, user interface

#42 fix crashing on close jar
  enigma-swing/src/main/java/cuchaz/enigma/gui/ClassSelector.java
Labels: bug, user interface

#36 redo notification system
  enigma-server/src/main/java/cuchaz/enigma/network/ClientPacketHandler.java
  enigma-server/src/main/java/cuchaz/enigma/network/EnigmaServer.java
  enigma-server/src/main/java/cuchaz/enigma/network/ServerMessage.java
  enigma-server/src/main/java/cuchaz/enigma/network/packet/EntryChangeC2SPacket.java
  enigma-server/src/main/java/cuchaz/enigma/network/packet/LoginC2SPacket.java
  enigma-server/src/main/java/cuchaz/enigma/network/packet/MessageC2SPacket.java
  enigma-server/src/main/java/cuchaz/enigma/network/packet/MessageS2CPacket.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/ClassSelector.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/Gui.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/GuiController.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/NotificationManager.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/config/UiConfig.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/dialog/AbstractDialog.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/dialog/ConnectToServerDialog.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/dialog/CreateServerDialog.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/dialog/JavadocDialog.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/docker/AllClassesDocker.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/docker/CallsTreeDocker.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/docker/CollabDocker.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/docker/DeobfuscatedClassesDocker.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/docker/Docker.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/docker/ImplementationsTreeDocker.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/docker/InheritanceTreeDocker.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/docker/NotificationsDocker.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/docker/ObfuscatedClassesDocker.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/docker/StructureDocker.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/docker/component/VerticalFlowLayout.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/elements/ConvertingTextField.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/elements/MenuBar.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/elements/ValidatablePasswordField.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/elements/ValidatableTextArea.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/elements/ValidatableTextField.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/elements/ValidatableUi.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/panels/IdentifierPanel.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/renderer/MessageListCellRenderer.java
  enigma/src/main/java/cuchaz/enigma/utils/validation/Message.java
  enigma/src/main/java/cuchaz/enigma/utils/validation/ParameterizedMessage.java
  enigma/src/main/java/cuchaz/enigma/utils/validation/PrintNotifier.java
  enigma/src/main/java/cuchaz/enigma/utils/validation/PrintValidatable.java
  enigma/src/main/java/cuchaz/enigma/utils/validation/Validatable.java
  enigma/src/main/java/cuchaz/enigma/utils/validation/ValidationContext.java
  enigma/src/main/resources/lang/en_us.json
Labels: enhancement, user interface

#46 fix mapping stats generation crash
  enigma-swing/src/main/java/cuchaz/enigma/gui/stats/StatsGenerator.java
Labels: bug, user interface

#49 fix classes docker collapsing on rename
  enigma-swing/src/main/java/cuchaz/enigma/gui/Gui.java
Labels: bug, user interface

#44 restore previously open mappings and jar when reopening enigma
  enigma-swing/src/main/java/cuchaz/enigma/gui/Gui.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/GuiController.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/Main.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/NotificationManager.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/config/UiConfig.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/elements/MenuBar.java
  enigma/src/main/java/cuchaz/enigma/utils/validation/Message.java
  enigma/src/main/java/cuchaz/enigma/utils/validation/ParameterizedMessage.java
  enigma/src/main/resources/lang/en_us.json
Labels: enhancement, user interface

#54 French translation
  enigma/src/main/resources/lang/fr_fr.json
Labels: enhancement, user interface

#65 fix calls tree navigation crash
  enigma-swing/src/main/java/cuchaz/enigma/gui/GuiController.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/docker/CallsTreeDocker.java
Labels: bug, user interface

#60 show mapping status in class tree
  enigma-swing/src/main/java/cuchaz/enigma/gui/ClassSelector.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/Gui.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/GuiController.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/node/ClassSelectorClassNode.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/stats/StatsGenerator.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/stats/StatsResult.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/util/GuiUtil.java
  enigma-swing/src/main/resources/icons/deobfuscated.svg
  enigma-swing/src/main/resources/icons/obfuscated.svg
  enigma-swing/src/main/resources/icons/partially_deobfuscated.svg
  enigma-swing/src/main/resources/icons/pending_status.svg
  enigma/src/main/java/cuchaz/enigma/EnigmaProject.java
Labels: enhancement, user interface

#57 fix extra name validation
  enigma-swing/src/main/java/cuchaz/enigma/gui/GuiController.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/dialog/JavadocDialog.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/newabstraction/EntryValidation.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/panels/IdentifierPanel.java
  enigma/src/main/java/cuchaz/enigma/translation/mapping/EntryRemapper.java
  enigma/src/main/java/cuchaz/enigma/translation/mapping/MappingValidator.java
  enigma/src/main/java/cuchaz/enigma/utils/validation/ValidationContext.java
Labels: bug, backend, user interface

#52 ask for confirmation for warnings in the gui
  enigma-swing/src/main/java/cuchaz/enigma/gui/NotificationManager.java
  enigma/src/main/java/cuchaz/enigma/utils/validation/ParameterizedMessage.java
  enigma/src/main/java/cuchaz/enigma/utils/validation/PrintNotifier.java
  enigma/src/main/java/cuchaz/enigma/utils/validation/ValidationContext.java
Labels: enhancement, user interface

#51 draggable docker buttons
  enigma-swing/src/main/java/cuchaz/enigma/gui/Gui.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/config/UiConfig.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/docker/AbstractInheritanceTreeDocker.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/docker/AllClassesDocker.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/docker/CallsTreeDocker.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/docker/CollabDocker.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/docker/DeobfuscatedClassesDocker.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/docker/Dock.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/docker/Docker.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/docker/ImplementationsTreeDocker.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/docker/InheritanceTreeDocker.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/docker/NotificationsDocker.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/docker/ObfuscatedClassesDocker.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/docker/StructureDocker.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/docker/component/DockerButton.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/docker/component/DockerLabel.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/docker/component/DockerSelector.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/docker/component/Draggable.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/docker/component/RightAngleLayerUI.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/elements/MainWindow.java
Labels: enhancement, user interface
