Repository QuiltMC/enigma, pull requests merged in 2023-12, with the labels that each got.

#166 put overall stats in stats dialog
  enigma-swing/src/main/java/org/quiltmc/enigma/gui/dialog/StatsDialog.java
  enigma/src/main/resources/lang/en_us.json
Labels: enhancement, user interface

#164 add `getId` method to `EnigmaService`
  enigma/src/main/java/org/quiltmc/enigma/api/Enigma.java
  enigma/src/main/java/org/quiltmc/enigma/api/EnigmaPluginContext.java
  enigma/src/main/java/org/quiltmc/enigma/api/EnigmaServices.java
  enigma/src/main/java/org/quiltmc/enigma/api/service/EnigmaService.java
  enigma/src/main/java/org/quiltmc/enigma/api/service/JarIndexerService.java
  enigma/src/main/java/org/quiltmc/enigma/api/service/NameProposalService.java
  enigma/src/main/java/org/quiltmc/enigma/api/source/Decompilers.java
  enigma/src/main/java/org/quiltmc/enigma/api/translation/mapping/EntryMapping.java
  enigma/src/main/java/org/quiltmc/enigma/impl/analysis/BuiltinPlugin.java
  enigma/src/test/java/org/quiltmc/enigma/name_proposal/TestNameProposal.java
  enigma/src/test/java/org/quiltmc/enigma/translation/mapping/TestReadWriteCycle.java
Labels: enhancement, backend

#167 move to quilt config
  enigma-server/src/main/java/org/quiltmc/enigma/network/EnigmaServer.java
  enigma-swing/build.gradle
  enigma-swing/src/main/java/org/quiltmc/enigma/gui/Gui.java
  enigma-swing/src/main/java/org/quiltmc/enigma/gui/GuiController.java
  enigma-swing/src/main/java/org/quiltmc/enigma/gui/Main.java
  enigma-swing/src/main/java/org/quiltmc/enigma/gui/config/Config.java
  enigma-swing/src/main/java/org/quiltmc/enigma/gui/config/ConfigPaths.java
  enigma-swing/src/main/java/org/quiltmc/enigma/gui/config/Decompiler.java
  enigma-swing/src/main/java/org/quiltmc/enigma/gui/config/DecompilerConfig.java
  enigma-swing/src/main/java/org/quiltmc/enigma/gui/config/DockerConfig.java
  enigma-swing/src/main/java/org/quiltmc/enigma/gui/config/KeyBindConfig.java
  enigma-swing/src/main/java/org/quiltmc/enigma/gui/config/KeyBindsConfig.java
  enigma-swing/src/main/java/org/quiltmc/enigma/gui/config/NetConfig.java
  enigma-swing/src/main/java/org/quiltmc/enigma/gui/config/StatsSection.java
  enigma-swing/src/main/java/org/quiltmc/enigma/gui/config/Themes.java
  enigma-swing/src/main/java/org/quiltmc/enigma/gui/config/UiConfig.java
  enigma-swing/src/main/java/org/quiltmc/enigma/gui/config/keybind/KeyBinds.java
  enigma-swing/src/main/java/org/quiltmc/enigma/gui/config/theme/LookAndFeel.java
  enigma-swing/src/main/java/org/quiltmc/enigma/gui/config/theme/Theme.java
  enigma-swing/src/main/java/org/quiltmc/enigma/gui/config/theme/Themes.java
  enigma-swing/src/main/java/org/quiltmc/enigma/gui/dialog/ConnectToServerDialog.java
  enigma-swing/src/main/java/org/quiltmc/enigma/gui/dialog/CreateServerDialog.java
  enigma-swing/src/main/java/org/quiltmc/enigma/gui/dialog/FontDialog.java
  enigma-swing/src/main/java/org/quiltmc/enigma/gui/dialog/JavadocDialog.java
  enigma-swing/src/main/java/org/quiltmc/enigma/gui/dialog/StatsDialog.java
  enigma-swing/src/main/java/org/quiltmc/enigma/gui/dialog/decompiler/VineflowerSettingsDialog.java
  enigma-swing/src/main/java/org/quiltmc/enigma/gui/docker/Dock.java
  enigma-swing/src/main/java/org/quiltmc/enigma/gui/docker/Docker.java
  enigma-swing/src/main/java/org/quiltmc/enigma/gui/docker/DockerManager.java
  enigma-swing/src/main/java/org/quiltmc/enigma/gui/docker/component/DockerButton.java
  enigma-swing/src/main/java/org/quiltmc/enigma/gui/docker/component/DockerSelector.java
  enigma-swing/src/main/java/org/quiltmc/enigma/gui/element/EditorTabbedPane.java
  enigma-swing/src/main/java/org/quiltmc/enigma/gui/element/MenuBar.java
  enigma-swing/src/main/java/org/quiltmc/enigma/gui/event/ThemeChangeListener.java
  enigma-swing/src/main/java/org/quiltmc/enigma/gui/highlight/SelectionHighlightPainter.java
  enigma-swing/src/main/java/org/quiltmc/enigma/gui/panel/EditorPanel.java
  enigma-swing/src/main/java/org/quiltmc/enigma/gui/renderer/CallsTreeCellRenderer.java
  enigma-swing/src/main/java/org/quiltmc/enigma/gui/renderer/ImplementationsTreeCellRenderer.java
  enigma-swing/src/main/java/org/quiltmc/enigma/gui/renderer/InheritanceTreeCellRenderer.java
  enigma-swing/src/main/java/org/quiltmc/enigma/gui/util/GuiUtil.java
  enigma-swing/src/main/java/org/quiltmc/enigma/gui/util/ScaleUtil.java
  enigma/build.gradle
  enigma/src/main/java/org/quiltmc/enigma/api/config/ConfigContainer.java
  enigma/src/main/java/org/quiltmc/enigma/api/config/ConfigSection.java
  enigma/src/main/java/org/quiltmc/enigma/impl/config/ConfigSerializer.java
  enigma/src/main/java/org/quiltmc/enigma/impl/config/ConfigStructureVisitor.java
  enigma/src/main/resources/lang/de_de.json
  enigma/src/main/resources/lang/en_us.json
  enigma/src/main/resources/lang/fr_fr.json
  enigma/src/main/resources/lang/ja_jp.json
  enigma/src/test/java/org/quiltmc/enigma/ConfigTest.java
  gradle/libs.versions.toml
Labels: enhancement, backend, user interface, removal

#168 2.0 API and impl changes for name proposal
  enigma-swing/build.gradle
  enigma-swing/src/main/java/org/quiltmc/enigma/gui/Gui.java
  enigma-swing/src/main/java/org/quiltmc/enigma/gui/GuiController.java
  enigma-swing/src/main/java/org/quiltmc/enigma/gui/Main.java
  enigma-swing/src/main/java/org/quiltmc/enigma/gui/element/MenuBar.java
  enigma/src/main/java/org/quiltmc/enigma/api/EnigmaProject.java
  enigma/src/main/java/org/quiltmc/enigma/api/analysis/index/jar/EntryIndex.java
  enigma/src/main/java/org/quiltmc/enigma/api/translation/mapping/EntryRemapper.java
  enigma/src/main/java/org/quiltmc/enigma/api/translation/mapping/IndexEntryResolver.java
  enigma/src/main/java/org/quiltmc/enigma/api/translation/mapping/tree/DeltaTrackingTree.java
  enigma/src/main/java/org/quiltmc/enigma/api/translation/mapping/tree/MergedEntryMappingTree.java
  enigma/src/main/java/org/quiltmc/enigma/api/translation/mapping/tree/MergedMappingTreeNode.java
  enigma/src/main/java/org/quiltmc/enigma/api/translation/representation/entry/Entry.java
  enigma/src/main/java/org/quiltmc/enigma/api/translation/representation/entry/MethodEntry.java
  enigma/src/main/java/org/quiltmc/enigma/util/EntryTreePrinter.java
  enigma/src/main/resources/lang/en_us.json
  enigma/src/test/java/org/quiltmc/enigma/name_proposal/TestNameProposal.java
Labels: enhancement, backend, wip

#169 Keep JAR_PROPOSED mappings separate from other proposals
  enigma-server/src/main/java/org/quiltmc/enigma/network/DedicatedEnigmaServer.java
  enigma-swing/src/main/java/org/quiltmc/enigma/gui/GuiController.java
  enigma/src/main/java/org/quiltmc/enigma/api/EnigmaProject.java
  enigma/src/main/java/org/quiltmc/enigma/api/translation/mapping/EntryRemapper.java
Labels: bug, backend

#171 Tokenize the ASM bytecode view
  enigma/src/main/java/org/quiltmc/enigma/api/analysis/EntryReference.java
  enigma/src/main/java/org/quiltmc/enigma/api/source/DecompiledClassSource.java
  enigma/src/main/java/org/quiltmc/enigma/api/source/SourceIndex.java
  enigma/src/main/java/org/quiltmc/enigma/impl/source/bytecode/BytecodeClassEntry.java
  enigma/src/main/java/org/quiltmc/enigma/impl/source/bytecode/BytecodeSource.java
  enigma/src/main/java/org/quiltmc/enigma/impl/source/bytecode/BytecodeSourceIndex.java
  enigma/src/main/java/org/quiltmc/enigma/impl/source/bytecode/EnigmaTextifier.java
  enigma/src/main/java/org/quiltmc/enigma/util/Pair.java
Labels: enhancement, user interface

#172 fixes to mappings index
  enigma/src/main/java/org/quiltmc/enigma/api/analysis/index/mapping/MappingsIndex.java
  enigma/src/main/java/org/quiltmc/enigma/api/analysis/index/mapping/PackageIndex.java
  enigma/src/main/resources/lang/en_us.json
Labels: bug, backend

#173 Add a couple more development options
  enigma-swing/src/main/java/org/quiltmc/enigma/gui/config/Config.java
  enigma-swing/src/main/java/org/quiltmc/enigma/gui/config/DevSection.java
  enigma-swing/src/main/java/org/quiltmc/enigma/gui/element/MenuBar.java
  enigma-swing/src/main/java/org/quiltmc/enigma/gui/panel/IdentifierPanel.java
  enigma/src/main/java/org/quiltmc/enigma/api/source/DecompiledClassSource.java
  enigma/src/main/java/org/quiltmc/enigma/util/EntryTreePrinter.java
  enigma/src/main/resources/lang/en_us.json
Labels: enhancement, user interface
