Repository QuiltMC/enigma, pull requests merged in 2024-10, with the labels that each got.

#227 fix a bunch of parameter javadoc issues
  enigma-swing/src/main/java/org/quiltmc/enigma/gui/GuiController.java
  enigma/src/main/java/org/quiltmc/enigma/api/translation/mapping/serde/tinyv2/TinyV2Writer.java
  enigma/src/main/java/org/quiltmc/enigma/impl/source/vineflower/EnigmaJavadocProvider.java
  enigma/src/test/java/org/quiltmc/enigma/input/interfaces/Inheritor.java
  enigma/src/test/java/org/quiltmc/enigma/input/interfaces/Root.java
  enigma/src/test/java/org/quiltmc/enigma/translation/mapping/TestMethodOverrideParamJavadoc.java
Labels: bug, backend

#232 Navigator now correctly handles new mapped items
  enigma-swing/src/main/java/org/quiltmc/enigma/gui/GuiController.java
  enigma-swing/src/main/java/org/quiltmc/enigma/gui/element/NavigatorPanel.java
  enigma-swing/src/main/java/org/quiltmc/enigma/gui/panel/EditorPanel.java
Labels: bug, user interface

#233 better logging and smarter behaviour for drop invalid mappings
  enigma-cli/src/main/java/org/quiltmc/enigma/command/DropInvalidMappingsCommand.java
  enigma-cli/src/test/java/org/quiltmc/enigma/command/DropInvalidMappingsTest.java
  enigma-cli/src/test/java/org/quiltmc/enigma/command/HelpCommandTest.java
  enigma-cli/src/test/resources/drop_invalid_mappings/expected/EmptyMappings.mapping
  enigma-cli/src/test/resources/drop_invalid_mappings/expected/InvalidMappings.mapping
  enigma-cli/src/test/resources/drop_invalid_mappings/input/EmptyMappings.mapping
  enigma-cli/src/test/resources/drop_invalid_mappings/input/InvalidMappings.mapping
  enigma/src/main/java/org/quiltmc/enigma/api/EnigmaProject.java
  enigma/src/main/java/org/quiltmc/enigma/api/analysis/index/jar/EntryIndex.java
  enigma/src/main/java/org/quiltmc/enigma/impl/translation/mapping/MappingsChecker.java
Labels: enhancement, backend, cli
