Repository QuiltMC/enigma, pull requests merged in 2025-01, with the labels that each got.

#245 extra proposal context
  enigma-cli/src/main/java/org/quiltmc/enigma/command/InsertProposedMappingsCommand.java
  enigma-server/src/main/java/org/quiltmc/enigma/network/DedicatedEnigmaServer.java
  enigma-swing/src/main/java/org/quiltmc/enigma/gui/GuiController.java
  enigma/src/main/java/org/quiltmc/enigma/api/Enigma.java
  enigma/src/main/java/org/quiltmc/enigma/api/EnigmaProject.java
  enigma/src/main/java/org/quiltmc/enigma/api/service/NameProposalService.java
  enigma/src/main/java/org/quiltmc/enigma/api/translation/mapping/EntryRemapper.java
  enigma/src/main/java/org/quiltmc/enigma/impl/plugin/BuiltinPlugin.java
  enigma/src/main/java/org/quiltmc/enigma/impl/plugin/RecordComponentProposalService.java
  enigma/src/test/java/org/quiltmc/enigma/name_proposal/TestFallbackNameProposal.java
  enigma/src/test/java/org/quiltmc/enigma/name_proposal/TestNameProposal.java
  enigma/src/test/java/org/quiltmc/enigma/name_proposal/TestNameProposalBypassValidation.java
  enigma/src/testFixtures/java/org/quiltmc/enigma/test/plugin/TestEnigmaPlugin.java
Labels: enhancement, backend

#248 fix drop invalid taking 2 runs to resolve a certain drop
  enigma-cli/src/test/java/org/quiltmc/enigma/command/DropInvalidMappingsTest.java
  enigma-cli/src/test/resources/drop_invalid_mappings/expected/Enums.mapping
  enigma-cli/src/test/resources/drop_invalid_mappings/input/Enums.mapping
  enigma/src/main/java/org/quiltmc/enigma/api/EnigmaProject.java
  enigma/src/main/java/org/quiltmc/enigma/impl/translation/mapping/MappingsChecker.java
Labels: bug, backend, cli

#251 Update .editorconfig to better enforce checkstyle
  .editorconfig
Labels: enhancement
