Repository QuiltMC/enigma, pull requests merged in 2025-08, with the labels that each got.

#255 add 'count fallback' option for stats and add stat icon settings
  enigma-cli/src/main/java/org/quiltmc/enigma/command/PrintStatsCommand.java
  enigma-swing/src/main/java/org/quiltmc/enigma/gui/Gui.java
  enigma-swing/src/main/java/org/quiltmc/enigma/gui/GuiController.java
  enigma-swing/src/main/java/org/quiltmc/enigma/gui/config/Config.java
  enigma-swing/src/main/java/org/quiltmc/enigma/gui/config/StatsSection.java
  enigma-swing/src/main/java/org/quiltmc/enigma/gui/dialog/StatsDialog.java
  enigma-swing/src/main/java/org/quiltmc/enigma/gui/element/ClassTreeCellRenderer.java
  enigma-swing/src/main/java/org/quiltmc/enigma/gui/element/MenuBar.java
  enigma-swing/src/main/java/org/quiltmc/enigma/gui/element/StatsTooltipPanel.java
  enigma-swing/src/main/java/org/quiltmc/enigma/gui/node/ClassSelectorClassNode.java
  enigma/src/main/java/org/quiltmc/enigma/api/service/NameProposalService.java
  enigma/src/main/java/org/quiltmc/enigma/api/stats/GenerationParameters.java
  enigma/src/main/java/org/quiltmc/enigma/api/stats/StatsGenerator.java
  enigma/src/main/resources/lang/en_us.json
  enigma/src/test/java/org/quiltmc/enigma/TestInnerClassParameterStats.java
  enigma/src/test/java/org/quiltmc/enigma/TestJarIndexEnums.java
  enigma/src/test/java/org/quiltmc/enigma/name_proposal/TestFallbackNameProposal.java
  enigma/src/test/java/org/quiltmc/enigma/records/TestRecordStats.java
  enigma/src/test/java/org/quiltmc/enigma/stats/TestStatGenerationInheritance.java
  enigma/src/test/java/org/quiltmc/enigma/stats/TestStatsGeneration.java
Labels: enhancement, backend, user interface

#266 add a search bar to the structure panel
  enigma-swing/src/main/java/org/quiltmc/enigma/gui/config/keybind/KeyBinds.java
  enigma-swing/src/main/java/org/quiltmc/enigma/gui/config/theme/Theme.java
  enigma-swing/src/main/java/org/quiltmc/enigma/gui/docker/StructureDocker.java
  enigma-swing/src/main/java/org/quiltmc/enigma/gui/element/EditorPopupMenu.java
  enigma/src/main/java/org/quiltmc/enigma/api/analysis/tree/StructureTreeNode.java
  enigma/src/main/java/org/quiltmc/enigma/api/analysis/tree/StructureTreeOptions.java
Labels: enhancement, user interface

#277 Command refactor
  enigma-cli/src/main/java/org/quiltmc/enigma/command/Argument.java
  enigma-cli/src/main/java/org/quiltmc/enigma/command/CheckMappingsCommand.java
  enigma-cli/src/main/java/org/quiltmc/enigma/command/Command.java
  enigma-cli/src/main/java/org/quiltmc/enigma/command/CommandsUtil.java
  enigma-cli/src/main/java/org/quiltmc/enigma/command/CommonArguments.java
  enigma-cli/src/main/java/org/quiltmc/enigma/command/ComposeMappingsCommand.java
  enigma-cli/src/main/java/org/quiltmc/enigma/command/ComposedArgument.java
  enigma-cli/src/main/java/org/quiltmc/enigma/command/ConvertMappingsCommand.java
  enigma-cli/src/main/java/org/quiltmc/enigma/command/DecompileCommand.java
  enigma-cli/src/main/java/org/quiltmc/enigma/command/DeobfuscateCommand.java
  enigma-cli/src/main/java/org/quiltmc/enigma/command/DropInvalidMappingsCommand.java
  enigma-cli/src/main/java/org/quiltmc/enigma/command/FillClassMappingsCommand.java
  enigma-cli/src/main/java/org/quiltmc/enigma/command/HelpCommand.java
  enigma-cli/src/main/java/org/quiltmc/enigma/command/InsertProposedMappingsCommand.java
  enigma-cli/src/main/java/org/quiltmc/enigma/command/InvertMappingsCommand.java
  enigma-cli/src/main/java/org/quiltmc/enigma/command/Main.java
  enigma-cli/src/main/java/org/quiltmc/enigma/command/MapSpecializedMethodsCommand.java
  enigma-cli/src/main/java/org/quiltmc/enigma/command/PrintStatsCommand.java
  enigma-cli/src/test/java/org/quiltmc/enigma/command/DropInvalidMappingsTest.java
  enigma-cli/src/test/java/org/quiltmc/enigma/command/HelpCommandTest.java
  enigma/src/testFixtures/java/org/quiltmc/enigma/TestUtil.java
Labels: refactor, cli
