Repository QuiltMC/enigma, pull requests merged in 2025-02, with the labels that each got.

#250 Fix deobfuscation icons not updating after initial stat generation completes
  enigma-swing/src/main/java/org/quiltmc/enigma/gui/GuiController.java
  enigma-swing/src/main/java/org/quiltmc/enigma/gui/docker/Dock.java
  enigma-swing/src/main/java/org/quiltmc/enigma/gui/docker/DockerManager.java
Labels: bug, user interface

#259 Minor wording changes to the discard mappings dialog
  enigma-swing/src/main/java/org/quiltmc/enigma/gui/Gui.java
  enigma-swing/src/main/java/org/quiltmc/enigma/gui/element/MenuBar.java
  enigma/src/main/resources/lang/en_us.json
Labels: user interface, translation

#258 Fix bug in ClassProvider
  enigma/src/main/java/org/quiltmc/enigma/api/class_provider/ClassProvider.java
  enigma/src/test/java/org/quiltmc/enigma/TestTokensSimilarClassNames.java
  enigma/src/test/java/org/quiltmc/enigma/input/similar_class_names/Alpha.java
  enigma/src/test/java/org/quiltmc/enigma/input/similar_class_names/Alphabet.java
  enigma/src/test/java/org/quiltmc/enigma/input/similar_class_names/Caller.java
  enigma/src/test/resources/proguard-similar_class_names-test.conf
Labels: bug, backend

#264 Fix non-letter keys starting a rename
  enigma-swing/src/main/java/org/quiltmc/enigma/gui/panel/EditorPanel.java
Labels: bug, user interface, p: low

#254 Fix methods obfuscated as "new" not creating their tokens
  buildSrc/build.gradle
  enigma-swing/src/test/resources/tinylog.properties
  enigma/build.gradle
  enigma/src/main/java/org/quiltmc/enigma/api/translation/mapping/EntryMapping.java
  enigma/src/main/java/org/quiltmc/enigma/impl/source/cfr/EnigmaDumper.java
  enigma/src/main/java/org/quiltmc/enigma/impl/source/vineflower/EnigmaTextTokenCollector.java
  enigma/src/test/java/org/quiltmc/enigma/DecompilationTest.java
  enigma/src/test/java/org/quiltmc/enigma/TokenChecker.java
  enigma/src/test/java/org/quiltmc/enigma/input/Keep.java
  enigma/src/test/java/org/quiltmc/enigma/input/decompiler/TestInvalidIdentifiers.java
  enigma/src/test/java/org/quiltmc/enigma/input/decompiler/TestVarargsDecompile.java
  enigma/src/test/resources/mappings-decompiler.txt
  enigma/src/test/resources/proguard-decompiler-test.conf
Labels: backend, p: low
